[[bookmark]]
key = "p"
path = "~/Documents/pdfs/"

[[bookmark]]
key = "c"
path = "/Users/hanyu_yan/Documents/Courses/"

[[bookmark]]
key = "l"
path = "~/Documents/Latex/"

[[bookmark]]
key = "e"
path = "/etc"
